CREATE TABLE MEMBER(
	ID		VARCHAR(255) NOT NULL,
	NAME	VARCHAR(255),
	AGE		INTEGER,
	PRIMARY KEY(ID)
);

INSERT INTO MEMBER VALUES(
	'id1', '오소리', 10
);

INSERT INTO MEMBER VALUES(
	'id2', '오소리', 30
);